### ISSUE TITLE
Sorting Data before writing to final file

### ISSUE THREAD

**Issue by DrewMcArthur** [DrewMcArthur/ai-trust-testbed#8]
When iterating through the middle files, {LABELS, HORSES, RACES}.data.csv, they might not necessarily be in the same order. 

adjust compile_data.py to write the labels and horses in the same order so that we can simply skip if the two don't line up.

**Comment by GeoAEngel** [comment]
Alphabetize races by horse name to match order, so that middle files are sorted by track, date, race, horse name.

**Comment by DrewMcArthur** [comment]
possibly devise a separate function for creating the two-horse-per-entry datafile

that would read the RACES file in the outer loop, then while the raceID for the horse file is the same, read horses and labels.  when the raceid is different, we read a new race.  For each race, we have to generate the horse pairs to write to file

**Comment by DrewMcArthur** [comment]
Sorting the middle files shouldn't be necessary, as they all get written to in the same order, if the traversal happens all at once.

**Comment by DrewMcArthur** [comment]
no longer necessary due to #12
